apiVersion: apps/v1

kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  replicas: 3
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
        - image: wordpress
          name: wordpress
          resources:
                requests:
                  memory: "250Mi"
                  cpu: "50m"
                limits:
                  memory: "500Mi"
                  cpu: "100m"
          env:
          - name: WORDPRESS_DB_HOST
            value: "192.168.219.121"
          - name: WORDPRESS_DB_NAME
            value: "waplz"
          - name: WORDPRESS_DB_USER
            value: "waplzuser"
          - name: WORDPRESS_DB_PASSWORD
            value: "1234"
          ports:
            - containerPort: 80
              name: wordpress
          volumeMounts:
            - name: wordpress-persistent-storage
              mountPath: /var/www/html
      volumes:
        - name: wordpress-persistent-storage
          persistentVolumeClaim:
            claimName: wordpress-volumeclaim
